vadimdemedes/ink

lib/h.js
test/h.js

React has a similar warning. Ran into it when working on #3

Throw when component is missing

---

readme.md

Show an example `.babelrc` for setting JSX pragma to `h`, and specify the necessary babel plugin.

add docs example for setting JSX pragma to `h`

---

index.js
test/render.js

Hello, 
This pull request closes issue #40. It check if the current env is TTY then attach `stdin` / `stdout` events and settings.
Here's what I did to test these changes : 
```
node index.js
node index.js | cat
```
Both are printing and exiting the script successfully.
Side note, I tried to launch tests but it failed because of a "loose" option with babel. Just ask me if I should create an issue about this or if I just miss something.

Disable input in a non-tty environment

---

readme.md

I'm a huge fan of Ink, and was excited at the possibility of using familiar patterns to build command-line apps. To that end, I've built my own implementations of react-router (and accordingly react-broadcast) to make developing Ink applications even sweeter.
I'm open to pull requests, suggestions and issue reports, and I hope my contribution to this ecosystem is welcome and useful to some!

Add ink-router and ink-broadcast to Useful Components in README

---

index.js
lib/components/bold.js
lib/components/color.js
lib/components/underline.js
test/components.js

Implements https://github.com/vadimdemedes/ink/issues/65
Renames the Text component to Color since it can be used to wrap any type of component. Also adds Bold and Underline components for those styles that can be achieved with chalk.
Also updates the tests and adds tests for those new components.

Rename Text to Color

---

readme.md

I created a small component that can animate text, which uses [chalk-animation](https://github.com/bokub/chalk-animation) under the hood. This PR adds a link to the project in the README.

Add 'ink-text-animation' to the README

---

index.js
lib/renderer.js

Fixes #61
the `Renderer` class takes a tree as an argument when constructed (`new Renderer(tree)`). It implements `EventEmitter` and emits an `update` event every time the tree updates. 
This makes creates an easy way to render a component with its lifecycle and get updates without involving stdin/stdout. 
The classic render method is re-written using this class, and calls the log-update's `log` with the updated component on `update`.

Create Renderer class

---

index.js
lib/h.js
package.json
readme.md
test/components.js

Fixes #46
This adds support for using the new React Fragments `<></>`. 
However: `plugin-transform-react-jsx` only supports them from babel v7 and on, which has no moved to `@babel/plugin-transform-react-jsx`, which requires `@babel/core`, which would mean `@babel/register` should be used instead of `babel-register`. Again, in order to use babel 7, ava had to be bumped to use the new `1.0.0-beta` versions. 
Coulnd't get xo to play nice with the fragments. I kept getting this error:
```
test/components.js:672:6
✖  672:6  Parsing error: Unexpected token >  
```
Maybe @sindresorhus can help me figure out how to get xo to recognize them.
This would also mean that every package that uses ink, should also upgrade to the new babel versions. 
A less invasive way of introducing fragments would be …

Support JSX fragments

---

index.d.ts

`waitUntilExit` is a function that returns a promise, rather than a promise itself

Fix waitUntilExit TypeScript definition

---

index.d.ts
readme.md
src/components/App.js
src/instance.js
src/render.js
test/exit.js
test/fixtures/exit-on-exit-with-error.js
test/fixtures/exit-raw-on-exit-with-error.js

Passing a result to `exit` will cause `waitUntilExit` to reject
with the value as the error.
Fixes #163.

Allow passing an error on exit

---

src/components/App.js
test/exit.js
test/fixtures/exit-with-thrown-error.js

This ensures that any errors in child components can be
handled gracefully by the app with a proper Error.

Add componentDidCatch and exit if render throws

---

readme.md

Wanted to update `ink-select` to use Ink 2.0, but I can't think of anything that would be different from `ink-select-input` so I'm not sure what to do with it. Instead I made a `ink-multi-select` component, based on the `ink-select-input` which pretty much does the same as the outdated `ink-checkbox-list`.

Add ink-multi-select to useful components

---

readme.md

[Ink-divider](https://github.com/JureSotosek/ink-divider) has been migrated to `Ink 2.0` as of https://github.com/JureSotosek/ink-divider/pull/3
Big thanks to @LitoMore 🎉

Move ink-divider to useful components

---

index.d.ts
readme.md
src/components/App.js
test/components.js

This pull request tries to implement the fixes discussed in https://github.com/vadimdemedes/ink/issues/166
There are not yet any tests, as I'd like to get feedback on whether this is the route to go 👍 
A thing that is concerning is that it would be nice to have useful errors for the situation in https://github.com/vadimdemedes/ink-text-input/issues/25, while an application that supports running in CI might want to just ignore setRawMode.

Fix setRawMode with non-TTY stdin and expose isRawModeSupported on StdinContext

---

readme.md

Followup to #172 - this PR adds a warning to the readme that indicates that `setRawMode` might throw depending on the value of `isRawModeSupported`.
Felt like this might be useful 👍

Add warning to check support before calling setRawMode

---

readme.md

[ink-table](https://github.com/maticzav/ink-table) has been migrated to Ink 2.0 as of https://github.com/maticzav/ink-table/pull/31.

Move ink-table to useful components

---

src/components/Color.js
test/components.js

Even though only dev error, it's convenient to not have to guard against temporarily empty strings getting passed to <Color>.
Obviously, this is just a suggestion and one of many ways to implement. It's easy enough to write a wrapper around <Color> to handle this if that's preferred.
The specific use case is rendering of fields in color that may, at times, be empty strings.
I don't use Typescript, so sorry if this breaks something in that world.

Don't error on empty string input to <Color>

---

package.json

Hello,
Ink's dependency on the `0.13.2` version of the scheduler causes an error when using some React hooks : [documented here](https://github.com/facebook/react/issues/15647).
This PR bumps the scheduler version to `0.15.0`

Update scheduler version.

---

index.d.ts
package.json
readme.md
src/calculate-wrapped-text.js
src/components/Box.js
src/components/Static.js
src/experimental/apply-style.js
src/experimental/dom.js
src/experimental/output.js
src/experimental/reconciler.js
src/experimental/renderer.js
src/instance.js
src/renderer.js
test/components.js
test/fixtures/ci.js
test/fixtures/exit-double-raw-mode.js
test/fixtures/exit-normally.js
test/fixtures/exit-on-exit-with-error.js
test/fixtures/exit-on-exit.js
test/fixtures/exit-on-finish.js
test/fixtures/exit-on-unmount.js
test/fixtures/exit-raw-on-exit-with-error.js
test/fixtures/exit-raw-on-exit.js
test/fixtures/exit-raw-on-unmount.js
test/fixtures/exit-with-thrown-error.js
test/helpers/render-to-string.js
test/reconciler.js

This work has started after issue on Gatsby's repo was raised about performance implications of using Ink - https://github.com/gatsbyjs/gatsby/issues/15505.
Currently Ink regenerates the entire layout on each render and rebuilds the output as well. This involves recreating all Yoga nodes, which can become expensive as number and frequency of renders grows.
This PR introduces a new experimental reconciler, which only updates necessary bits of the Yoga layout tree on every render. It still rebuilds output from layout every time, but now Ink limits amount of writes into terminal output to 60 frames per second, which should be more than enough for CLIs, which should mitigate that tradeoff.
Author of the Gatsby issue above reported a significant speedup when using this reconciler and I'd …

Add new experimental reconciler

---

index.d.ts
readme.md
src/hooks/use-app.js
src/hooks/use-stdin.js
src/hooks/use-stdout.js
src/index.js
test/components.js
test/flex-align-items.js
test/flex-justify-content.js

Refs #137.
```js
import {useApp, useStdin, useStdout} from 'ink';
...
const {exit} = useApp();
const {stdin, isRawModeSupported, setRawMode} = useStdin();
const {stdout} = useStdout();
```

Add `useApp`, `useStdin` and `useStdout` hooks

---

examples/counter/counter.js

`setInterval` should be explicit about the interval. While not required since it defaults to 10, this brings it in-line with README example.

Updates timer to run like the README.md example

---

package.json

Introduced when adding typescript support https://github.com/vadimdemedes/ink/pull/136/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R43.
Adding `@types/react` to the `dependencies` is _great_. It allows users of the `ink` package to not worry about types. The react types are included automagically. However, having **multiple** `@types/react` in the dependency chain can cause havoc in a project, as `@types/react` tries to modify globals (specifically JSX globals). `tsc` will fail, noting that there are multiple declarations of X, Y and Z, where these are all the globals that are modified.
Having multiple `@types/react` in the chain happens for example when hoisting, when using workspaces, when using monorepos etc. Additionally, a user _should_ be able to provide their own `@types/react` …

Remove `@types/react` from dependencies

---

readme.md

Add a link to [`ink-markdown`](https://github.com/cameronhunter/ink-markdown) in the "Useful Components" section

Add ink-markdown to the readme

---

readme.md

Add "Useful Hooks" section and a link to [`ink-use-stdout-dimensions`](https://github.com/cameronhunter/ink-monorepo/tree/master/packages/ink-use-stdout-dimensions).

Mention `ink-use-stdout-dimensions` in the readme

---

package.json

This should remove one of the warnings about `@types/react` missing that I get on `npm install`:
This is basically what Sindre did for `auto-bind`: https://github.com/sindresorhus/auto-bind/commit/66a053fbc3782b425e98693c0a78b22847e724c1
Ideally, we'd also upgrade the dependency on `auto-bind` itself from `3.0.0` to `4.0.0`, so that the change I linked is included.

Move `@types/react` to be an optional peer dependency

---

src/render-node-to-output.js
test/components.js

Ink currently (since the [improvements to alignment](https://github.com/vadimdemedes/ink/compare/v2.4.0...v2.5.0?diff=unified#diff-38693372290cabd092ab6ade4a4db655) in 2.5.0) throws an error when trying to squash text nodes with zero child nodes. This PR avoids that error by bailing out early on empty text nodes.
Fixes #241

Fix error when squashing empty text nodes

---

package.json
readme.md
src/components/Box.tsx
src/components/Color.tsx
src/components/Text.tsx
src/components/Transform.tsx
src/dom.ts
src/index.ts
src/reconciler.ts
src/render-node-to-output.ts
test/components.tsx
test/deprecated.tsx

This component allows transforming a string representation of React components
before they are written to output. It's not a new functionality, previously it
was exposed via undocumented `unstable__transformChildren` prop in <Box> and
<Text> components.
I think it has been proven to be stable and there are definitely use cases
for it, so it's time to let anyone leverage this feature.
Now deprecated `unstable_transformChildren` prop is still going to be available
and work as before to maintain backwards compatibility. However, it will be
removed in future major versions.

Add <Transform> component

---

src/components/Color.tsx
src/components/Text.tsx
src/components/Transform.tsx

Since all of these components are pure (don't have side effects), it's safe to
memoize their output. This means that the output of these components will be
rerendered only when their props change.
This small optimization results in a nice performance boost in Ink's rendering
process - from ~3,6k ops/sec to ~4,6k ops/sec.

Memoize <Color>, <Text> and <Transform> components

---

benchmark/static/index.js
benchmark/static/static.js
examples/jest/jest.js
readme.md
src/components/Static.tsx
src/dom.ts
src/index.ts
src/ink.tsx
src/reconciler.ts
src/render-node-to-output.ts
src/renderer.ts
test/components.tsx
test/fixtures/ci.tsx
test/fixtures/erase-with-static.tsx
test/render.tsx

Previous implementation of `<Static>` component was performing poorly for apps
with thousands of items to render. Ink's rendering process slowed down
proportionally to the number of children in `<Static>` component, because
React has to call `React.createElement()` for each child, even if it was already
rendered. See https://github.com/gatsbyjs/gatsby/pull/21955#discussion_r387703540
for more context.
This change changes the API of a `<Static>` component to call `React.createElement()`
and render only new items, ignoring the items that were already rendered.
The new API is looking very similar to virtual list libraries.
You pass a list of items to render via `items` prop and specify a function
that is responsible for rendering each item, the rest is handled for you.
```jsx
<Static …
```

Implement a new <Static> component

---

package.json
src/ink.tsx
src/log-update.ts

`log-update` module wraps output on every render, which slows down performance
of Ink apps. Ink doesn't need that and some other functionality, because it
handles wrapping itself, so `log-update` is essentially performing the same
work twice.
This change adds a forked and stripped down version of `log-update` with the
plan to merge the changes upstream in the future.

Use a fork of log-update for displaying output

---

src/get-max-width.ts
src/render-node-to-output.ts
test/components.tsx
test/padding.tsx

Fixes regression from https://github.com/vadimdemedes/ink/pull/276.
If padding is taken into account when calculating max width of parent container
to decide whether to wrap text or not, it results in invalid text wrapping.
For example, if there's a "Hello World" text that fits inside container,
adding padding to that container will basically subtract max width of it
and cause text wrapping when it's not needed.
This change removes padding from max width calculation.

Fix text wrapping inside padded container

---

package.json
src/get-max-width.ts
src/render-node-to-output.ts
test/components.tsx
test/margin.tsx
test/padding.tsx

As part of this change #283 is reverted.
That PR incorrectly changed padding behavior to expand container dimensions,
instead of shrinking available space for its content, which is not what Yoga does.
This PR restores the original behavior, consistent with Yoga. It also fixes
support for newlines (`\n`) in text when there's padding or text wrapping.
After this change, all lines in text will have correct padding.

Fix padding with newlines and text wrapping

---

examples/use-stdout/index.js
examples/use-stdout/use-stdout.js
package.json
readme.md
src/components/App.tsx
src/components/StdoutContext.ts
src/ink.tsx
test/fixtures/use-stdout.tsx
test/hooks.tsx

I encountered a use case when people wanted to proxy `console.log()` and
`console.error()` to stdout and stderr respectively. Previously, they could
use `<Static>` component for this, but it only supports stdout. Adding stderr
support to `<Static>` turned out to not be viable, because it's still part of
CLI's output.
Instead, considering the specificity of this community request, I went for a
simpler solution - let you write any string to stdout and stderr.
Behavior is essentially the same as `<Static>`, except it results in much smaller
performance implications due to the fact that `write()` only accepts strings,
not React components.
This change adds support for stdout, support for stderr will be added separately.
```jsx
import {useStdout} from 'ink';
const MyApp = () => {
const {write} …
```

Add write() function to write any string to stdout

---

examples/use-focus/index.js
examples/use-focus/use-focus.js
readme.md
src/components/App.tsx
src/components/FocusContext.ts
src/devtools.ts
src/hooks/use-focus-manager.ts
src/hooks/use-focus.ts
src/index.ts
test/focus.tsx

This PR adds a simple focus management mechanism to Ink. It's based on @jdeniau's work in https://github.com/vadimdemedes/ink/pull/262 and [Focus Management RFC](https://github.com/reactjs/rfcs/issues/104) in React.
You can check out the documentation for changes made here in https://github.com/vadimdemedes/ink/tree/focus#usefocusoptions, but the gist is that components can call `useFocus()` hook to notify Ink that they can be focused and when user presses <kbd>Tab</kbd>, Ink is going to move focus between focusable components.
```js
import {useFocus} from 'ink';
const FocusableComponent = () => {
const {isFocused} = useFocus();
// `isFocused` will equal `true` after user presses Tab and this component receives focus
return <Text>{isFocused ? 'I am focused' : 'I am not focused'}</Text>; …
```

Add focus management

---

package.json
readme.md
src/ink.tsx
src/render.ts

This PR extracts console patching code into [patch-console](https://github.com/vadimdemedes/patch-console) module and exposes a `patchConsole` option to disable it (it's enabled by default). It's useful when users want to implement custom loggers and don't want Ink's handling of it.

Extract console patching and make it configurable

---

src/ink.tsx
src/renderer.ts
test/components.tsx
test/errors.tsx
test/focus.tsx
test/helpers/create-stdout.ts
test/helpers/render-to-string.ts
test/reconciler.tsx
test/render.tsx

Fixes https://github.com/vadimdemedes/ink/issues/153.
It works well when resizing up, but not so much with resizing down. Previous output doesn't get erased correctly, because when terminal shrinks, it also shrinks previous output, so `log-update` no longer knows how many lines to erase. I'm going to accept this tradeoff for now, because resizing down rarely works in any CLI with full-width UI.

Rerender on resize

---

src/devtools.ts

I found import ink will override the global.window provided by my jsdom setup.  It would be nice to check first before set it globally.

Don't override existing global.window or global.WebSocket

---

src/components/Box.tsx
src/components/Newline.tsx
src/components/Static.tsx
src/components/Text.tsx
src/components/Transform.tsx
src/dom.ts
src/global.d.ts
src/ink.tsx
src/reconciler.ts
src/render-node-to-output.ts
src/squash-text-nodes.ts
test/fixtures/ci.tsx
test/fixtures/clear.tsx
test/fixtures/console.tsx
test/fixtures/erase-with-static.tsx
test/fixtures/erase.tsx
test/fixtures/exit-double-raw-mode.tsx
test/fixtures/exit-normally.tsx
test/fixtures/exit-on-exit-with-error.tsx
test/fixtures/exit-on-exit.tsx
test/fixtures/exit-on-finish.tsx
test/fixtures/exit-on-unmount.tsx
test/fixtures/exit-raw-on-exit-with-error.tsx
test/fixtures/exit-raw-on-exit.tsx
test/fixtures/exit-raw-on-unmount.tsx
test/fixtures/exit-with-thrown-error.tsx
test/fixtures/use-input-multiple.tsx
test/fixtures/use-input.tsx
test/fixtures/use-stdout.tsx

Fixes https://github.com/vadimdemedes/ink/issues/164.
Ink now uses custom `<ink-box>` and `<ink-text>` tags to ensure no one uses `<div>` or `<span>`, which are leftovers from Ink 1.x. However, you still mustn't use those, they are reserved for internal use only.

Remove usage of <div> and <span>

---

src/reconciler.ts

Did a `<Static>` benchmark and noticed that memory was steadily climbing, because removed Yoga nodes weren't deleted from memory. This PR fixes that.

Free memory from unused Yoga nodes

---

readme.md
src/components/Box.tsx
src/index.ts
src/measure-element.ts
test/measure-element.tsx

Fixes https://github.com/vadimdemedes/ink/issues/168. cc @maticzav 
From readme:
> Use `measureElement()` function if you need to measure dimensions of a particular `<Box>` element.
It returns an object with `width` and `height` properties.
This function is useful when your component needs to know the amount of available space it has before it can start rendering or when you need to change your layout based on the length of the content.
```jsx
import {Box, measureElement} from 'ink';
const Example = () => {
const ref = useRef();
useEffect(() => {
const {width} = measureElement(ref.current);
}, []);
return (
<Box width={100}>
<Box ref={ref}>{/* This box will stretch to 100 width */}</Box>
</Box>
);
};
```

Add measureElement() API

---

src/components/ErrorOverview.tsx

See https://github.com/vadimdemedes/ink/issues/311#issuecomment-647223222.
If source maps are enabled, error stack could point to a file that doesn't actually exist in the distributed code. This PR fixes that by checking if there's a file, before attempting to read it.

Fix error handler with non-existent file path in the stack

---

src/components/Text.tsx
src/components/Transform.tsx
test/components.tsx
test/text.tsx

I encountered a case where `<Text/>` would be updated to `<Text>X</Text>`, but layout would be broken. I traced it down to `undefined` and `null` not being handled by `<Text>` and `<Transform>`. This PR ensures that there are no nodes added when there's no children in these components.

Ignore <Text> and <Transform> components with falsy children

---

src/ink.tsx

Fixes #325 by using 80 columns if `process.stdout.columns` is `undefined`.

Fall back to 80 columns if the width of the terminal cannot be determined

---

src/components/ErrorOverview.tsx

I was testing Ink 3.0.0-4 and I had an error in my application. However, instead of showing the new ErrorOverview it showed an Ink error:
(TypeError: Cannot read property 'function' of null at ink/build/components/ErrorOverview.js:78:106)
Looking at the source code, it seems that a parseLine() function can return null, but that null values are not handled.
After this MR, it shows the line unparsed if it cannot be parsed - which makes sure that no error data gets lost.
Looks like that there is still some stuff that can be done to handle React errors better (and also parse Component data). But at least this handles the case where parseLine returns null, which should be handled either way.

Make sure that stack lines that cannot be parsed don't break the ErrorOverview

---

src/components/Box.tsx

By explicitly typing `Box` as `React.FC` the `ref` prop is removed from typings. Instead let TypeScript infer the type from the return type of the `forwardRef()` function. (in this case `ForwardRefExoticComponent`)
To make sure `Box` still has the "children" prop, wrap `Props` in `PropsWithChildren<>`.
Fixes #329

Fix type of `<Box>` to include `ref` prop

---

readme.md

The [Terraform CDK](https://github.com/hashicorp/terraform-cdk) got [released](https://www.hashicorp.com/blog/cdk-for-terraform-enabling-python-and-typescript-support/) yesterday, and it's using ink for the CLI UI

Add Terraform CDK

---

src/components/Text.tsx

In the JetBrains IDEs would suggest colors like the above image.
But, in VSCode it does not work. 😨
This may not be complete, but it would help JetBrains IDE users.

Improve auto-complete for `color` and `backgroundColor` props for `Text`

---

readme.md
src/hooks/use-input.ts
test/fixtures/use-input.tsx
test/hooks.tsx

I'm working on a pager, and wanted to be able to check for page up / page down events, and thought it'd be a common enough thing to make a PR.

Add support to `useInput` for Page Up and Page Down keys

---

src/reconciler.ts
test/borders.tsx

Fixes https://github.com/vadimdemedes/ink/issues/340.
In the following scenario, border wouldn't be rendered after the update happens:
```jsx
const Test = () => {
const [borderColor, setBorderColor] = useState();
useEffect(() => {
setBorderColor('green');
}, []);
return (
<Box borderStyle="round" borderColor={borderColor}>
<Text>Hello World</Text>
</Box>
);
};
```
It was happening because Ink's reconciler passes down only props that were changed during an update (https://github.com/vadimdemedes/ink/blob/master/src/reconciler.ts#L160) and in this case, `borderStyle` remained unchanged so it was missing when Ink drew a layout. If Ink doesn't see `borderStyle`, it's not going to render the border - https://github.com/vadimdemedes/ink/blob/master/src/render-border.ts#L7.
To fix it, I modified …

Fix border re-rendering

---

src/index.ts

Export `DOMElement` type to use `React.useRef<DOMElement>` (#350)

Export DOMElement type

---

src/components/App.tsx
src/components/StdinContext.ts
src/hooks/use-input.ts
test/fixtures/use-input-ctrl-c.tsx
test/hooks.tsx

Fixes https://github.com/vadimdemedes/ink/issues/349.
Issue was caused by https://github.com/vadimdemedes/ink/blob/373db19bdbbbab0e7fedf11dc2285cbe6cd3bd45/src/hooks/use-input.ts#L183-L185, where Ctrl + C sequence was ignored by [`useInput`](https://github.com/vadimdemedes/ink#useinputinputhandler-options). However, if [`exitOnCtrlC`](https://github.com/vadimdemedes/ink#exitonctrlc) is disabled, that means developer wants to handle exiting manually, so `useInput` should no longer suppress it.

Let `useInput` handle Ctrl+C if `exitOnCtrlC` is disabled

---

examples/static/static.js

Variable `timer` is undefined.
Variable `timer` should get the setTimeout return in order to be used in clear timeout on clean up function.

Fix `Static` example code

---

src/ink.tsx

Fixes #366. 
Side note: As I said in that issue, `node.yogaNode.getComputedWidth` returns `0`, but I didn't touch that. This single change solves my issue.
Related:
- #325
- #327
cc @bartlangelaan

Fallback to 80 if number of columns isn't set

---

readme.md

I have recently discovered Ink, and I was amazed by the concept, awesome work 👍
While experimenting with Ink, I have built a git contributions calendar for local repositories.  
Feel free to include it on the "Who's using Ink" README section if you wish.

Add git-contrib-calendar link on "Who's using Ink" section

---

src/styles.ts

Type of `borderColor` property in `Styles` interface can (and should) match the `color` property of `Text` component, but it did not. It was limited to basic foreground colors without the option use string values.

Fix `borderColor` type

---

src/devtools.ts
src/reconciler.ts

As discussed in #384.
However, after also converting the `ws` module import to `require()` to avoid loading unused code, I basically had the whole `devtools.ts` wrapped in an `if` block. At that point, I decided to roll back my changes to that file and just go for conditionally importing the whole devtools file.
Fixes #384

Import devtools only when DEV=true

---

readme.md

Now we can also create a TypeScript project by passing a `--typescript` option.
Related to https://github.com/vadimdemedes/create-ink-app/pull/5

Update `create-ink-app` guide

---

src/components/Static.tsx

Static accepts styles in `props.style`, not directly on props.

Fix `<Static>` typings

---

src/components/App.tsx
test/focus.tsx

@vadimdemedes 
Ran into an issue where `focusNext` was called in a side-effect, but the focusables (children) were unmounted before it fired, resulting in this error. Just adding some undefined checks
```
error The above error occurred in the <InternalApp> component:
in InternalApp
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
/Users/milesj/Projects/packemon/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
throw ex;
^
TypeError: Cannot read property 'id' of undefined
at App.<anonymous> (/Users/milesj/Projects/packemon/node_modules/ink/build/components/App.js:119:70)
at getStateFromUpdate (/Users/milesj/Projects/packemon/node_modules/react-reconciler …
```

Fix undefined errors for focusing unmounted elements

---

readme.md

Add link to [ink-syntax-highlight](https://github.com/vsashyn/ink-syntax-highlight) component to readme.

Add link to ink-syntax-highlight in readme

---

src/components/Text.tsx

Hello, 
I read the issue(#428) and would like to suggest a solution to this
Chalk's backgroundColor type is declared as follows.
https://github.com/chalk/chalk/blob/main/index.d.ts#L31-L49
```js
export type BackgroundColor =
| 'bgBlack'
| 'bgRed'
| 'bgGreen'
| 'bgYellow'
| 'bgBlue'
| 'bgMagenta'
| 'bgCyan'
| 'bgWhite'
| 'bgGray'
| 'bgGrey'
| 'bgBlackBright'
| 'bgRedBright'
| 'bgGreenBright'
| 'bgYellowBright'
| 'bgBlueBright'
| 'bgMagentaBright'
| 'bgCyanBright'
| 'bgWhiteBright';
```
However, in ink, there is a code to attach bg prefix (https://github.com/vadimdemedes/ink/blob/master/src/colorize.ts#L8-L14),
so there is no need to attach bg.
Therefore, I suggest to use chalk's `ForegroundColor` type as auto-complete.

Fix the TypeScript type for the `backgroundColor` prop

---

package.json
src/output.ts
test/borders.tsx

Fixes #443
Fixes #369
Turns out the issue was that border rendering uses `string-length` which measures number of codepoints. In the case of wide character or emoji the length returns 1, which is incorrect because it occupies 2 cells. The fix is by replacing the measurement with `string-width` which measures number of cells (and it is already transitively used in other places where text is measured).
Notes:
- `string-length` was not used elsewhere, I removed it from package.json
- `string-width` is already pulled in transitively by other packages, so it does not increase dependencies when added as top-level entry

Fix box border rendering containing emojis and wide characters

---

readme.md

This `;` will cause error in actual code.

Fix `Box` example in the readme

---

readme.md

Fixes broken link to `use-focus-with-id` example.

Fix `use-focus-with-id` example link

---

package.json
src/reconciler.ts

Fixes #491.
Should possibly wrap https://github.com/vadimdemedes/ink/blob/763db800f6b93c0807b016c6dc1ac8cccef0a67b/src/reconciler.ts#L24-L30 into a more specific error as well?

Move `react-devtools-core` to optional peer dependency

---

package.json
test/fixtures/ci.tsx
test/fixtures/exit-on-exit-with-error.tsx
test/fixtures/exit-on-exit.tsx
test/fixtures/exit-on-finish.tsx
test/fixtures/exit-on-unmount.tsx

The declaration of `createContainer` in `@types/react-reconciler` has been changed since 0.16.4.
You can find its history versions here:
- https://www.jsdelivr.com/package/npm/@types/react-reconciler
- https://cdn.jsdelivr.net/npm/@types/react-reconciler@0.26.4/index.d.ts
- https://cdn.jsdelivr.net/npm/@types/react-reconciler@0.26.3/index.d.ts

Fix types and linting errors

---

readme.md
src/components/Box.tsx
src/output.ts
src/reconciler.ts
src/render-node-to-output.ts
src/styles.ts
test/overflow.tsx

This PR adds `overflowX`, `overflowY` and `overflow` props to `Box` component to hide any content overflowing the element's bounds. Allowed values are `visible` (default) and `hidden`.
This is a follow up PR to https://github.com/vadimdemedes/ink/pull/393. Credit to @tin-t for submitting an initial implementation of this feature, which this PR is based on!
Everyone is welcome to try it out!

Allow configuring overflow behavior in `Box` component

---

package.json
src/output.ts
test/borders.tsx

Fixes #505 
The problem is happening due to (I think) `yoga` and `slice-ansi` incompatibility on string indexes. `slice-ansi` counts emojis as 1 char and `yoga` counts it as 2 (again, I think).
Here I'm using `emoji-regex` (which was already pulled in by other dependencies so it doesn't add any real new package to the dependency tree) to count emojis on the current line. Then I'm substracting that amount to the `x` variable (starting offset on where to replace the string).
If you find a better way to fix this issue please let me know and I'll be happy to try it out and implement it here.
Before: 
After:

Fix broken layout when emojis are used

---

readme.md
src/components/Box.tsx
src/styles.ts
test/gap.tsx

Fixes https://github.com/vadimdemedes/ink/issues/538.
Since #550 has landed, Ink can now support [`gap`](https://developer.mozilla.org/en-US/docs/Web/CSS/gap) property.
```jsx
<Box gap={1}>
<Text>A</Text>
<Text>B</Text>
</Box>
//=> A B
```

Support `gap` in `Box`

---

src/dom.ts
src/reconciler.ts
test/borders.tsx

[`style`](https://github.com/vadimdemedes/ink/blob/2a67354222affbc1728fd55f2faaede8ddd899c0/src/dom.ts#L13) property of Ink nodes contains the changed fields of `style` object, rather than a full `style` object itself. As a result, `style` in internal representation of an Ink node is inconsistent what's actually passed via a [`style`](https://github.com/vadimdemedes/ink/blob/2a67354222affbc1728fd55f2faaede8ddd899c0/src/components/Box.tsx#L116) prop to `ink-box` (rendered by `Box`) or `ink-text` (rendered by `Text`).
Here's example code demonstrating the problem:
```jsx
const {rerender} = render(<Box borderStyle="round" borderColor="green"/>);
// Box's style = { borderStyle: 'round', borderColor: 'green' }
// Ink node's style = { borderStyle: 'round', borderColor: 'green' }
rerender(<Box …
```

Improve diffing of styles

---

src/components/Box.tsx
src/render-node-to-output.ts
src/styles.ts

This PR has no effect on the end user of Ink.
What it does is moves out `margin`, `padding` and `gap` props from being generated inside `Box` and into an `applyStyles` function that directly updates styles of a Yoga node.

Move shorthand `margin`, `padding` and `gap` props out of `Box`

---

readme.md
src/render-border.ts
src/styles.ts
test/borders.tsx

This is a continuation of https://github.com/vadimdemedes/ink/pull/431, thank you @kosciolek for this contribution!
This PR adds 4 new props to `Box`: `borderTop`, `borderRight`, `borderBottom` and `borderLeft`. They are all boolean props and they default to `true`. They let you control visibility of each border side.
For example, this won't show the left border:
```jsx
<Box borderStyle="round" borderLeft={false}>
<Text>Hello world</Text>
</Box>
```

Control visibility of individual border sides

---

readme.md
src/render-border.ts
src/styles.ts
test/borders.tsx

This PR updates `borderStyle` prop in `Box` to accept an object with this shape:
```ts
type BoxStyle = {
topLeft: string;
top: string;
topRight: string;
left: string;
bottomLeft: string;
bottom: string;
bottomRight: string;
right: string
}
```
For example:
```jsx
<Box
borderStyle={{
topLeft: '↘',
top: '↓',
topRight: '↙',
left: '→',
bottomLeft: '↗',
bottom: '↑',
bottomRight: '↖',
right: '←'
}}
>
<Text>Content</Text>
</Box>
```
This allows developers to customize how Ink renders borders around a `Box`, in case none of the built-in styles provided by [`cli-boxes`](https://github.com/sindresorhus/cli-boxes) don't fit.

Customize border style

---

package.json
src/hooks/use-input.ts
src/parse-keypress.ts
test/fixtures/use-input.tsx
test/hooks.tsx

Fixes https://github.com/vadimdemedes/ink/issues/409.
After working several days on figuring out and fixing all of the input parsing issues in `useInput`, I realized I'm just patching holes all the time and not really sure if I'm introducing more bugs with each change.
So I bailed on this and decided to copy the code from [enquirer](https://github.com/enquirer/enquirer), which I believe adapted it from [keypress](https://github.com/TooTallNate/keypress), which extracted it from Node.js itself.
I disabled linter on `src/parse-keypress.ts` to avoid fixing a lot of the issues it reported, which would make it harder to merge upstream changes.

Rework parsing keyboard input in `useInput`

---

src/hooks/use-input.ts

Currently, Ink will rerender as soon as state is updated. As a result, if a component has 2 `useState` hooks and both of them need to be updated at once, it will actually result in 2 rerenders, not 1.
```jsx
import React, {useState} from 'react';
import {render, useInput, Text} from 'ink';
function Example() {
const [x, setX] = useState(1);
const [y, setY] = useState(1);
useInput(input => {
if (input === 'i') {
setX(previousX => previousX + 1);
setY(previousY => previousY + 1);
}
});
return (
<Text>
X = {x} Y = {y}
</Text>
);
}
render(<Example/>, {debug: true});
```
Pressing <kbd>i</kbd> will lead to the following output:
```
X = 1 Y = 1
X = 2 Y = 1
X = 2 Y = 2
```
Ideally there shouldn't be an intermediate render for "X = 2 Y = 1", which occurs after `setX` is called and Ink should only …

Batch state updates in `useInput` callback

---

readme.md
src/render-border.ts
src/styles.ts
test/borders.tsx

This PR adds `borderDimColor` prop to `Box` for dimming the color of the border, similar to [`dimColor`](https://github.com/vadimdemedes/ink#dimcolor) in `Text` component.
```jsx
<Box borderStyle="round" borderDimColor>
<Text>Hello world</Text>
</Box>
```
There are also `borderTopDimColor`, `borderBottomDimColor`, `borderLeftDimColor` and `borderRightDimColor` props to dim the color of individual border sides.

Dim border colors

---

package.json
src/output.ts
test/overflow.tsx

This is a proof of concept for a different rendering approach that does not rely on `sliceAnsi` as heavily.
I tried this with my test component from #560, but with 50 spinners. Without this change, 50 spinners put one core of my CPU at 100%, and rendering lags heavily. With this change, I'm looking at ~40% utilization of one core, which is still not ideal, but renders fluently.
The output for 10s of profiling now looks like this, is idle half the time and most of the work is done in `wasm`, which is probably from `yoga` internals:
fixes: https://github.com/vadimdemedes/ink/issues/560
This will need some more testing with emojis and clipping, but I wanted to get this out for some early feedback.

Speed up generation of output

---

package.json

Fixes https://github.com/vadimdemedes/ink/issues/617

Update `ansi-tokenize` dependency to be compatible with Node.js v14.x again

---

readme.md
src/components/Transform.tsx
src/global.d.ts
src/output.ts
src/render-node-to-output.ts
src/squash-text-nodes.ts
test/components.tsx

This makes it possible to know which line is being transformed.
Fix: https://github.com/vadimdemedes/ink/issues/611
There are some linting errors, but I'm not sure how to go about fixing them. `for(;;)` (or maybe `.forEach()`) is the right thing to use here, since the index is relevant, but xo really wants to only ever see `for(of)`.

Add `index` property to Transform

---

src/components/App.tsx
src/components/StdinContext.ts
src/hooks/use-input.ts
test/components.tsx
test/focus.tsx

By doing testing of the Shopify CLI on Windows we found that `stdin` could get in a broken (paused) state if `pause` and `resume` were called in rapid succession by mounting and unmounting components that use `useInput`. Not all components would do this which leads me to believe it's a timing issue.
Here's a video showcasing one of our text prompts getting into this broken state.
https://github.com/vadimdemedes/ink/assets/151725/3b422178-e159-4119-854a-eb4ba25ab417
I've tracked down the issue and it seems like removing `pause` and `resume` and switching to the `readable` event fixes things. I don't think this project needs to keep supporting node <10 right? If so, this change should create no backwards compatibility issues.

Use stdin `readable` event instead of `data`

---

package.json
test/components.tsx

A bug has been introduced with the work done [here](https://github.com/vadimdemedes/ink/pull/564) and it relates to the tokenization of ansi escape characters. We noticed it with `ansiEscapes.link` and I added a test case in this repo which now fails. 
@AlCalzone I don't know enough about your `ansi-tokenize` project, but could this be fixed there?
Here's a screenshot of the failing test:
You can see from the screenshot that the link escape is not being closed properly so the link "leaks" in all the text after that.

Fix broken link escapes

---

src/components/App.tsx
test/components.tsx
test/focus.tsx

There is a bug I introduced with https://github.com/vadimdemedes/ink/pull/616
If someone invokes `render` once with a component that uses `useInput`, then everything works fine (and that's why tests are passing).
If instead you invoke `render`, wait for Ink to exit and then later in the execution you invoke it again with the same component, then node just quits because `stdin` has been dereferenced in the previous call to `render`.
With this PR I add a call to `ref` so that when the second call happens node stays up.

Fix inability to read user input after app exit

---

readme.md

Wallace CLI v3 was built from the ground up and no longer uses an external library to render some basic boxes, so it's time to say goodbye 😅
Thank you so much for this library and for the early opportunity to use it and giving Wallace a platform by showcasing it for many years in this readme. According to my analytics we've received 500+ visitors over the last years by this single line in the readme alone 🥰
This partially reverts 206f0b7c932ef7d48339f1d7abe9d53d4f1d1493 from September 2019 ;)

Remove Project Wallace from readme

---

readme.md
src/components/App.tsx
test/focus.tsx
tsconfig.json

When wrapping around at the beginning or end of the list of components, we should search respectively for the last or first _active_ component.
I didn't use `Array.prototype.findLast` because the `tsconfig` doesn't support it and it was simple enough to write a loop.

fix: only focus active elements

---

readme.md

Add npm-check-extras to "Who's Using Ink?"

---

readme.md

Without adding the optional dependency the process fails.

Improve devtools documentation

---

readme.md

I'm building a CLI wrapping other commands, using React (and the https://www.npmjs.com/package/ink) package and I built this library to orchestrate spawning child processes: https://github.com/kraenhansen/ink-spawn
This PR adds a link to it in the readme, along with other components made by the community.
Thanks for an awesome package 👍

Add `ink-spawn` to "Useful Components"

---

readme.md

The link to Shopify's Splash project in the documentation was broken. After investigating, it seems Shopify has stopped using the Splash script as indicated in [this pull request](https://github.com/Shopify/polaris/pull/4181).
This update removes the outdated link to ensure the documentation remains accurate and up-to-date.

Remove Shopify's Splash project from readme

---

src/parse-keypress.ts
test/fixtures/use-input.tsx
test/hooks.tsx

Strings that start with control characters (e.g.
"\rfoo") were previously parsed incorrectly and
treated as if it was a ctrl+letter combination.
Fixes #649.

Fix input parsing of control characters

---

package.json
src/dom.ts
src/get-max-width.ts
src/ink.tsx
src/reconciler.ts
src/render-node-to-output.ts
src/styles.ts

Fixes #647 by removing dependency on `yoga-wasm-web` and replacing it with `yoga-layout` package, updating imports, etc.

Update `yoga-wasm-web` dependency to `yoga-layout`

---

src/hooks/use-input.ts
test/fixtures/use-input.tsx
test/hooks.tsx

When I press the return key (`\r`) on macOS, the `key` object incorrectly indicates that the `shift` key is also pressed:
```js
{
input: '\r',
key: {
upArrow: false,
downArrow: false,
leftArrow: false,
rightArrow: false,
pageDown: false,
pageUp: false,
return: true,
escape: false,
ctrl: false,
shift: true,
tab: false,
backspace: false,
delete: false,
meta: false
}
}
```
The previous logic inferred the shift key was pressed for any single character where `input[0].toUpperCase() === input[0]`. This included not only uppercase letters, but also control characters (like `\r`) and symbols, leading to incorrect detection of the shift key.
This PR updates the shift key detection logic to use a regular expression (`/^[A-Z]$/`) that matches only uppercase ASCII letters. Now, `key.shift` will only …

fix: correctly detect shift key only for uppercase letters

---

src/devtools-window-polyfill.ts
src/ink.tsx
src/log-update.ts
test/fixtures/erase-with-state-change.tsx
test/render.tsx

When the outputHeight goes from a value ` >= stdout.rows` to a value `< stdout.rows` in between re-render, it is possible that the old content is not completely removed from the terminal. 
This happens for three reasons
1. We actually want to consider the previous output height when deciding to entirely clear the terminal or only delete several lines. If the current output has a `height >= stdout.rows`, but we only need to clear the previous render's output, there's no point in writing `ansiEscapes.clearTerminal`. Similarly, if the current output has a `height < stdout.rows` but the previous output exceeded `stdout.rows`, then writing `ansiEscapes.eraseLines(previousLineCount)` won't clear all of the old output.
2. `this.log.clear()` doesn't actually track the height of the output if we …

Fix stale output when outputHeight changes from above stdout.rows to below stdout.rows

---

src/reconciler.ts

In React 19 support PR #719 , logic for marking Static as dirty was [removed](https://github.com/vadimdemedes/ink/pull/719/files#diff-92cf748778b8e4481e8c7e0e81785c68bf04046c7b16192b7b4c185c58e9e2cbL251). I'm not sure why this was removed, but it prevents the Static component from being updated when new components are added to items.
I see React [removed prepareUpdate()](https://github.com/facebook/react/pull/26583) and asked developers to do the preparation in commitUpdate, however, the [commitUpdate](https://github.com/facebook/react/tree/main/packages/react-reconciler#commitupdateinstance-type-prevprops-nextprops-internalhandle) method doesn't provide root node. The solution is to add a global variable tracking the root node.

Fix a bug that causes static content to not be updated in time

---

readme.md

Several of the "live demo" Replit links now lead to a 404. I've removed them from the README file.
Here are the links I've removed:
- https://ink-counter-demo.vadimdemedes.repl.run/
- https://ink-jest-demo.vadimdemedes.repl.run/

Remove dead replit links from README

---

readme.md

Hi! I've added a project I've recently built using ink: https://github.com/darksworm/argonaut
I put it next to the other k8s-related project (kubelive), as that seems more logical than putting it at the bottom. 
quick preview of argonaut:
https://github.com/user-attachments/assets/96fb21b4-12c1-48f8-90cc-c947b07aec66
Thank you for considering adding my project to your list :)

Add argonaut to "Who's using Ink?"

---

readme.md

Add [ink-chart](https://github.com/pppp606/ink-chart) to the Useful Components section in the README.
ink-chart provides terminal visualization components for the Ink CLI framework:
- **Sparkline component** - For displaying inline charts
- **BarChart component** - For displaying bar charts
- Full **TypeScript support**
I am the author of this library.

docs(readme/useful-components): add ink-chart

---

src/ink.tsx
test/fixtures/fullscreen-no-extra-newline.tsx
test/render.tsx

Fixed an issue where an extra newline was added at the bottom of the screen in full-screen mode.
Fix #752, Related https://github.com/vadimdemedes/ink/pull/717
- Removed trailing newline from full-screen output
- Allow the bottom line of the terminal to be usable
- Added test to verify that the bottom line is correctly usable in full-screen mode

Fix extra newline in full-screen mode
