vadimdemedes/ink

.editorconfig
.gitignore
.npmrc
license
package.json
readme.md

Various meta tweaks and some text improvements.

Meta tweaks

---

lib/component.js
test/components.js

React passes props as the second argument to functional setState calls.

Pass props in setState() callback

---

readme.md

Thank you very nice library.
I tried to make a list of check box list.
Please merge this PR, if you'd like.

Add `ink-checkbox-list` to the readme

---

readme.md

This addresses issue #39, I've added some text to the `README.md` to give a quick explanation on what each generator does and how to install them.

Adding Documentation on Generators for Ink

---

readme.md

Hi! Thank you so much for the library! 
I created an autocomplete-like Text input component to search and select from list of objects.
Please, merge this PR if you like it!

Add ink-autocomplete and ink-table to Useful Components 

---

readme.md

I have added **ink-box** in the readme. @vadimdemedes Please have a look.

Add 'ink-box' to the readme

---

readme.md

Forgot to update this in the PR

Update readme for Color, Bold, Underline

---

readme.md

https://github.com/sindresorhus/ink-big-text

Add ink-big-text to Useful Components in readme

---

readme.md

Fix example in readme to use `<Color>`

---

readme.md

Hello @vadimdemedes 
Thank you so much for developing `Ink`. I had a blast playing with it and I created one custom component which I hope you will find useful. It was uploaded to npm as well. Please let me know if you wish me to do some extra tuning for the component. 
It would make me really happy if you could feature this component on the readme page for the project.

Added ink-quicksearch to readme

---

lib/component.js
test/render.js

fixes https://github.com/vadimdemedes/ink/issues/88

fix: queued state updates overwriting each other

---

readme.md

Weird, didn't find callback in the documentation :)

Add setState's callback to documentation

---

readme.md

Hey, I created a basic Ink components and thought you might be interested.
Merge the PR if you like it.😀
Also, I am open to any suggestions if you have any😏

Add ink-divider to list of useful components

---

package.json
src/create-reconciler.js

[v2/next] update deps to support hooks

---

readme.md

Thought I'd add a link to my new project 👍

Add Swiff to list of 'built with Ink'

---

readme.md

ink-figlet renders [figlet.js](https://www.npmjs.com/package/figlet) fonts as Ink components. It's a bit like ink-big-text, but with more fonts.

Readme: add ink-figlet

---

readme.md

Add [ink-color-pipe](https://github.com/LitoMore/ink-color-pipe) to `Related` section.
`ink-color-pipe` is a better solution to render some mutable color text, we could put all styles to one prop.
Screenshot:

Add related package - ink-color-pipe

---

index.d.ts
readme.md

Follow-up to https://github.com/vadimdemedes/ink/commit/e5f7322dda56c8c2dad79253f9d766842c05b93d

Fix minWidth/minHeight in readme and add TS types

---

index.d.ts

Add typings for "flexBasis" prop

---

src/instance.js
src/reconciler.js

Fixes https://github.com/vadimdemedes/ink/issues/139, see that issue for explanation behind this PR. I would appreciate if you tried it out in your Ink-based apps to see if there are any regressions!

Initialize reconciler once

---

readme.md

As discussed in https://github.com/vadimdemedes/pastel/issues/9.

Add example with using forms

---

readme.md

The example babel config is incomplete. This works, could save some other people time.

Improve the example Babel config in the readme

---

readme.md

We're in love with ink so we want to be on the list! 😄 ❤️

Add gatsby-cli to the list of "Built with Ink"

---

src/components/Static.js

Fix code comment typo

---

index.d.ts
index.test-d.tsx
package.json

I will add more type tests later on when I have more time. Just wanted to get it in so we can ask for type tests too for new features.

Add initial type tests

---

package.json
readme.md
src/experimental/output.js
src/experimental/renderer.js
src/instance.js
src/output.js
src/renderer.js
test/fixtures/erase-with-static.js
test/fixtures/erase.js
test/render.js

Fixes https://github.com/vadimdemedes/ink/issues/158.

Clear terminal if output is taller than viewport

---

examples/jest/jest.js
package.json
src/components/App.js
src/components/Text.js
test/helpers/run.js

Fixes #246
Tests are passing and I tested the examples and they seem to still work.

Upgrade dependencies

---

readme.md

:octocat: https://github.com/goliney/garson

Add `garson` to `Who's Using Ink` section

---

readme.md

Hi, thanks for Ink, very cool project!
Here's a quick PR to convert the first example to use hooks - what are your thoughts here?
I also have a repl.it sandbox based on https://repl.it/@vadimdemedes/ink-counter-demo, feel free to copy to yours:
https://repl.it/@karlhorky/SarcasticAwareAgent

Convert example to hooks

---

readme.md

Change wording in measureElement() description

---

migrate.md

Migration guide tweaks

---

readme.md

Removed "which is unreleased yet" phrase from readme.md since v3 has been released!

Removed 'which is unreleased yet' phrase

---

migrate.md
readme.md
src/reconciler.ts
test/components.tsx

Fixes https://github.com/vadimdemedes/ink/issues/337.

Throw error when <Box> is nested inside <Text> component

---

migrate.md

Fixes https://github.com/vadimdemedes/ink/issues/358.

Add text wrapping to migration guide

---

.github/workflows/test.yml
src/components/Static.tsx
test/components.tsx

Fixes https://github.com/vadimdemedes/ink/issues/354.

Fix `Static` rendering stale items on unmount

---

readme.md

Added GitGud under "Who's using Ink"

Add gitgud link to "Who's using Ink" section

---

examples/use-focus/use-focus.js

ERROR  Text string "Press Tab to focus next element, Shift+Tab to focus previous element, Esc to reset focus." must be rendered inside <Text> component

Fix error of text string outside text box in example

---

src/hooks/use-input.ts
test/fixtures/use-input.tsx
test/hooks.tsx

Some keyboards with separate delete key sends this sequence
Fixes #363

Add "Remove" escape keyboard sequence as delete key

---

readme.md

https://github.com/pranshuchittora/autarky

Add Autarky link to "Who's using Ink" section

---

readme.md

I've added the library ``ink-form`` (of which I am the developer) to the list of useful libraries in the readme file. Feel free to decline if you think this does not fit the scope of the list.

Add ink-form to useful components

---

readme.md

Added https://github.com/privatenumber/ink-task-list to the list

Add link to ink-task-list in readme

---

readme.md

Add [tasuku](https://github.com/privatenumber/tasuku)

Add tasuku to "Who's Using Ink?"

---

readme.md

Add [mnswpr](https://github.com/mordv/mnswpr)

Add mnswpr to "Who's Using Ink?"

---

readme.md

Add lrn to "Who's Using Ink?"

---

readme.md

❤️
Also using:
* ink-gradient
* ink-progress-bar
* ink-table
* ink-syntax-highlight
* ink-link
* ink-select-input
* ink-text-input

Add ToDesktop CLI to "Who's Using Ink?" section

---

readme.md
src/render-border.ts
src/styles.ts
test/borders.tsx

This PR allows `Box` to customize the border color of each side:
```jsx
<Box borderStyle="round" borderTopColor="green"/>
<Box borderStyle="round" borderRightColor="green"/>
<Box borderStyle="round" borderBottomColor="green"/>
<Box borderStyle="round" borderLeftColor="green"/>
```

Customize border color of each side

---

src/hooks/use-input.ts
test/fixtures/use-input.tsx

Fixes https://github.com/vadimdemedes/ink/issues/398.
This is a super simple alternative to https://github.com/vadimdemedes/ink/pull/445, which doesn't require as many changes to fix a simple bug like that. I like the approach taken in #445 though, so perhaps it could be shipped with a next major version.

Fix arrow and page up/down keys detected as meta keys

---

readme.md

Add [Walle](https://github.com/Pobepto/walle)

Add Walle to "Who's Using Ink?"

---

src/devtools-window-polyfill.ts

Fixes https://github.com/vadimdemedes/ink/issues/624.

Fix React Devtools integration

---

readme.md

Add [Sudoku](https://github.com/mrozio13pl/sudoku-in-terminal)

Add Sudoku to "Who's Using Ink?"

---

readme.md

Noticed this whe testing out ink. The timer was never cleared.

readme: fix timeout example

---

readme.md

Added the `Sea Trader` game to the "Who's using Ink?" section.

Add Sea Trader to "Who's Using Ink?"

---

readme.md

I saw Claude Code tool is also using ink!

Add Claude Code to "Who's Using Ink?"

---

readme.md

Added https://github.com/t1mmen/srtd to list of lib users.

Add srtd to "Who's Using Ink?"

---

readme.md

Codex is a recently released open-source coding agent terminal app made by OpenAI (as a competitor to Claude Code).

Add OpenAI Codex to "Who's using Ink?"

---

readme.md

https://github.com/Piebald-AI/tweakcc

Add tweakcc to Who's Using Ink?
